### ISSUE TITLE
Pass memory settings as kwargs rather than integers

### ISSUE THREAD

**Issue by lh64** [LoLab-VU/pysb-cupsoda#14]
Currently, allowed memory settings are 0 (global), 1 (global+shared), 2 (global+shared+constant). I would prefer these be set with keyword arguments that convey what they are. Maybe "g", "gs", "gsc" for 0, 1, and 2, respectively. Anyone have any thoughts?

**Comment by alubbock** [comment]
Explicit is better than implicit - I'd recommend having `memory_usage` take the arguments 'global', 'shared', or 'sharedconstant'.

**Comment by lh64** [comment]
I'm good with that
