### ISSUE TITLE
Run cupSODA multiple times if necessary

### ISSUE THREAD

**Issue by lh64** [LoLab-VU/pysb-cupsoda#5]
Currently, if the user passes more parameter sets ('c_matrix') than available threads on the GPU, cupSODA will simply exit with an error. It would be nice if PySB could automatically detect situations like this and run cupSODA multiple times in sequence. This will require querying the GPU architecture and having an accurate way to estimate the number of simulations that can fit on the device.

**Comment by alubbock** [comment]
Issue moved to pySB: https://github.com/LoLab-VU/pysb/issues/27
