### ISSUE TITLE
Make 'param_values' and 'y0' optional to conform to general simulator convention

### ISSUE THREAD

**Issue by lh64** [LoLab-VU/pysb-cupsoda#6]
If 'y0' or 'param_values' are not passed to the CupSodaSimulator, the code should should use the values from the model and assume that they are constant for all simulations. If neither are passed, it should assume only a single simulation and maybe throw a warning.

**Comment by alubbock** [comment]
Issue moved to pySB: https://github.com/LoLab-VU/pysb/issues/26
