### ISSUE TITLE
Improve verbosity handling

### ISSUE THREAD

**Issue by lh64** [LoLab-VU/pysb-cupsoda#8]
Output from our Python code is currently getting mixed with output from cupSODA, making it difficult to read the command line output. Also, cupSODA now supports three levels of verbose output. We should improve the verbosity handling to streamline all of this.

**Comment by alubbock** [comment]
The verbosity option on the github and souceforge versions appears to only take a boolean. Has that changed in a new version somewhere else @lh64 to take multiple levels?

**Comment by alubbock** [comment]
Issue moved to pySB repo: https://github.com/LoLab-VU/pysb/issues/25
